/*
	DECODEIT Schema 1.0.0.1
*/

USE WideWorldImporters

DROP TABLE CBSurveyInfo


CREATE TABLE CBSurveyInfo (
	[SurveyId] [INT] IDENTITY(1,1),
	[CustomerID] [INT] NOT NULL,
	[SURVEYDATE] [DATETIME] NOT NULL,
	[SURVEYQUESTION1] [VARCHAR] (50) NOT NULL,
	[ANSWER1] [VARCHAR] (50) NULL,
	[SURVEYQUESTION2] [VARCHAR] (50) NOT NULL,
	[ANSWER2] [VARCHAR] (50) NULL,
	[SURVEYQUESTION3] [VARCHAR] (50) NOT NULL,
	[ANSWER3] [VARCHAR] (50) NULL,
	[ISINTERESTED][BIT] NOT NULL ,
	CONSTRAINT [PK_SURVEYID] PRIMARY KEY CLUSTERED (
	[SURVEYID] ASC
	)
)
--TEST INSERT--

INSERT INTO [dbo].[CBSurveyInfo]
           ([CustomerID]
           ,[SURVEYDATE]
           ,[SURVEYQUESTION1]
           ,[ANSWER1]
           ,[SURVEYQUESTION2]
           ,[ANSWER2]
           ,[SURVEYQUESTION3]
           ,[ANSWER3]
           ,[ISINTERESTED])
     VALUES

		(1,'20230102','WOULD YOU LIKE TO BE A MENTOR','YES','DO YOU HAVE TRANSPORTATION','YES','WHAT IS YOUR ETHNICITY','ASIAN','TRUE'),
		(1,'20230102','WOULD YOU LIKE TO BE A MENTOR','YES','DO YOU HAVE TRANSPORTATION','YES','WHAT IS YOUR ETHNICITY','PACIFICISLANDER','TRUE'),
		(1,'20230102','WOULD YOU LIKE TO BE A MENTOR','YES','DO YOU HAVE TRANSPORTATION','YES','WHAT IS YOUR ETHNICITY','BLACK','TRUE'),
		(1,'20230102','WOULD YOU LIKE TO BE A MENTOR','YES','DO YOU HAVE TRANSPORTATION','YES','WHAT IS YOUR ETHNICITY','HISPANIC','TRUE'),
		(1,'20230102','WOULD YOU LIKE TO BE A MENTOR','YES','DO YOU HAVE TRANSPORTATION','YES','WHAT IS YOUR ETHNICITY','ASIAN','TRUE')

	

  UPDATE [dbo].[CBSurveyInfo]
   SET SURVEYDATE = '20230202'
   WHERE ANSWER3 = 'HISPANIC'

   DELETE FROM CBSurveyInfo
   WHERE ANSWER3 = 'ASIAN'

   SELECT [SurveyId]
      ,[CustomerID]
      ,[SURVEYDATE]
      ,[SURVEYQUESTION1]
      ,[ANSWER1]
      ,[SURVEYQUESTION2]
      ,[ANSWER2]
      ,[SURVEYQUESTION3]
      ,[ANSWER3]
      ,[ISINTERESTED]
  FROM [dbo].[CBSurveyInfo]
 
	 